version: v1
processing:
  configs:
    - name: automated
      extends: automated
      config:
        normalize: do_not_normalize
    - name: demo
      extends: default
      config:
        virus_scanning: false
