name: "Release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Semantic version to release (e.g., 1.2.3 or 1.2.3-rc.1)"
        required: true
        type: string

concurrency:
  group: release-${{ github.event.inputs.version }}
  cancel-in-progress: true

jobs:
  validate-version:
    name: Validate semantic version
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository
        uses: "actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8" # v6.0.1
        with:
          sparse-checkout: .github/actions/validate-semver
      - name: Validate semantic version
        uses: ./.github/actions/validate-semver
        with:
          version: ${{ github.event.inputs.version }}

  build-push-images:
    name: "Build and push images"
    runs-on: "ubuntu-24.04"
    needs: [validate-version]
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8" # v6.0.1
        with:
          submodules: recursive
      - name: "Create local tag"
        run: git tag ${{ github.event.inputs.version }}
      - name: "Set up QEMU"
        uses: "docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130" # v3.5.0
      - name: "Set up buildx"
        uses: "docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f" # v3.12.0
      - name: "Log in to Docker Hub"
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: "Log in to GitHub Container Registry"
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build and push ambox"
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          file: ./hack/box/Dockerfile
          tags: |
            artefactual/ambox:latest
            artefactual/ambox:${{ github.event.inputs.version }}
            ghcr.io/sevein/ambox:latest
            ghcr.io/sevein/ambox:${{ github.event.inputs.version }}

  release:
    name: Create GitHub release
    runs-on: ubuntu-24.04
    needs: [build-push-images]
    permissions:
      contents: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Push release tag
        run: |
          git tag ${{ github.event.inputs.version }}
          git push origin refs/tags/${{ github.event.inputs.version }}
      - name: Create GitHub Release
        uses: ./.github/actions/release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ github.event.inputs.version }}
          title: ${{ github.event.inputs.version }}
